Using 'sed' command removed
ipsilon/evm-benchmarks pull request #13
Opened 2022-11-08 16:35 UTC by rodiazet

2022-11-08 17:30 UTC, chfast requested changes

2022-11-08 17:30 UTC, chfast commented on Makefile
> -	@echo Patching t8ntool config with '${EVM}'
The whole target is not needed any more.

2022-11-08 17:30 UTC, chfast commented on Makefile
> +export PATH := $(BIN_DIR):$(PATH)
```suggestion
# Add local bin dir to PATH so the evm tool can be found by retesteth
export PATH := $(BIN_DIR):$(PATH)

```

2022-11-10 09:21 UTC, rodiazet commented on Makefile
> -	@echo Patching t8ntool config with '${EVM}'
Done

2022-11-10 13:27 UTC, chfast approved these changes

2022-11-10 13:28 UTC, merged